services:
  liquidui:
    image: guidcruncher/liquidui:latest
    extra_hosts:
      - liquidui:127.0.0.1
    network_mode: host
    userns_mode: keep-id
    user: 1001:1001
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 3010:3010
    environment:
      - TZ=Europe/London
      - BASE_PATH=http://192.168.1.202:3010
    container_name: liquidui
    hostname: liquidui
    restart: unless-stopped
    volumes:
      - ./:/app
